### ISSUE TITLE
Why the MaskedEditText class is not Editable?

### ISSUE THREAD

**Issue by Sunsiha** [egslava/edittext-mask#19]
For this issue [https://github.com/egslava/edittext-mask/issues/18](url) i tried to edit but the class is not Editable

**Comment by OsipXD** [comment]
I have same problem. I've added MaskedEditText but it isn't editable

**Comment by egslava** [comment]
The link isn't valid. Please, provide a mini description for the problem and I'll investigate.
@osipxd @Sunsiha

**Comment by egslava** [comment]
I'll close the issue till then.
