### ISSUE TITLE
Gradle install

### ISSUE THREAD

**Issue by MihaelIsaev** [egslava/edittext-mask#2]
How to install it with gradle?

**Comment by egslava** [comment]
Hi, Michael!
I'm so sorry, but I have not done Gradle support. Pull requests are always
welcome.

Don't know, but, perhaps, it's usable with jitpack.

**Comment by egslava** [comment]
`compile 'ru.egslava:MaskedEditText:${last_version_see_above_in_the_beginning}'`

A fresh version is always available on the [main page](https://github.com/egslava/edittext-mask).
