### ISSUE TITLE
How can i do like this way?

### ISSUE THREAD

**Issue by Sunsiha** [egslava/edittext-mask#26]
I need to add first letter should be letter and slash then full numbers only with 3 numbers . Ex : K/000

I have done like this way,
            <br.com.sapereaude.maskedEditText.MaskedEditText
                android:id="@+id/storeET"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@drawable/custom_spinner_background"
                android:hint="00000"
                android:inputType="text"
                android:padding="6dp"
                android:textColor="@color/grey"
                android:textSize="18sp"
                android:typeface="monospace"
                mask:keep_hint="true"
                mask:mask="#/###" />

  ```
  public static void maskedEditTextFontStoreCode(Activity activity, MaskedEditText rp_ipET) {
        Typeface face = Typeface.createFromAsset(activity.getAssets(),
                "segoeuil.ttf");
        rp_ipET.setTypeface(face);
        rp_ipET.setCharRepresentation('#');
        rp_ipET.setMask("#/###");
    }
```
Now i need to add to handle first letter should be Characters and rest 3 letter should be number.

**Comment by egslava** [comment]
@Sunsiha btw, what did you try to enter to the text field? Could we use it in FAQ/documentation?
