### ISSUE TITLE
При вводе +79276 вводит +7926

### ISSUE THREAD

**Issue by MihaelIsaev** [egslava/edittext-mask#3]
Привет!

Пытаюсь заюзать с маской "+7 (###) ###-##-##" и получаю трабл после ввода цифры 7.
Пишу "+7 (927" и как только ввожу следующую цифру, например 6, введенный текст становится "+7 (926".

Пытаюсь побороть уже часа три, но пока не удалось.
Проблема, как я вижу, тут 

```
private void initSymbolMask(){
        for (int i=0; i < mMask.length(); i++){
            char ch = mMask.charAt(i);
            if (ch != '#')
                symbolMask.add(String.valueOf(ch));
        }
    }
```

и соответственно потом тут

```
String str = Utils.unmask(s.toString(), symbolMask);
```

Можешь помочь?

**Comment by egslava** [comment]
Hi :-) You closed the issue. Is it still actual?

**Comment by egslava** [comment]
Hi, @MihaelIsaev !
I've tried to reproduce, but I couldn't.

This's the code I used to reproduce the error (from the example):
```xml
    <br.com.sapereaude.maskedEditText.MaskedEditText
        android:id="@+id/phone_input"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:inputType="phone"
        android:typeface="monospace"
        mask:allowed_chars="1234567890"
        mask:mask="+7(###)###-##-##"
        />
```

I also attached gif to show my behavior:

![edittext-mask-2017-03-04-061623](https://cloud.githubusercontent.com/assets/1143228/23572621/e3c61d8e-00a2-11e7-9f1a-1b6f09d078cc.gif)

What do I do wrong? If you have time, can you attach a sample project (that reproduces the error)?
