### ISSUE TITLE
Hint mask shows a wrong format

### ISSUE THREAD

**Issue by DimalPerera** [egslava/edittext-mask#37]
Hi,

According to my mask format, MaskedEditText hint should want to show 12345678-123456 but in hint string shows a wrong way (12345678--123456) when the application runs. It's contains 2 dash signs (12345678--123456). 

`<br.com.sapereaude.maskedEditText.MaskedEditText
                android:id="@+id/etJobName"
                style="@style/EditText_Style"
                android:layout_height="71dp"
                android:layout_marginTop="10dp"
                android:inputType="phone"
                android:typeface="monospace"
                app:allowed_chars="1234567890"
                app:mask="########-######"
                android:hint="12345678-123456"
                app:keep_hint="true"
                />`

**Comment by roskoff** [comment]
@DimalPerera change hint to `android:hint="12345678123456`, the mask will take care of the dash.
