### ISSUE TITLE
Copyright information

### ISSUE THREAD

**Issue by nerminator** [egslava/edittext-mask#42]
Can you please add your copyright information in the license file? 
If possible, we also need a tag for 1.0.5 version in the git repository.

**Comment by egslava** [comment]
@nerminator , he-he, I hardly understand what you're talking about :) I'm not into law, so, if you guide me with more details, I'll appreciate a lot :)

**Comment by nerminator** [comment]
Your first line in your License file starts with "The MIT License (MIT)..."
License File:
https://github.com/egslava/edittext-mask/blob/master/LICENSE
Just after that line put something like:
Copyright (c) 2018 YourName YourSurname

You can put company name or any other name if you do not want to give your name. Some people give their website name for example.
You can have a look at the following license file for reference:
https://github.com/afollestad/material-dialogs/blob/master/LICENSE.txt

And we need a tag for 1.0.5 please, if it is possible

**Comment by egslava** [comment]
Sorry, it took me quite long to response :) But:
1. The file you're pointing to is no longer available.
2. If it's still actual, [version 1.0.5](https://github.com/egslava/edittext-mask/releases/tag/v1.0.5) now is available.
