### ISSUE TITLE
Can I mask with (XXX) XXX-XXXX ext.XXX this format ?

### ISSUE THREAD

**Issue by jayesh28589** [egslava/edittext-mask#47]
Hello,

How can I mask with below format ?

(XXX) XXX-XXXX ext.XXXXXX        i.e (654) 321-5846 ext.654321

Thanks.

**Comment by egslava** [comment]
Hello! What a problem? I haven't tried the code, but it should be possible to be done this way:
```XML
  <br.com.sapereaude.maskedEditText.MaskedEditText
    android:id="@+id/phone_input"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:inputType="phone"
    android:typeface="monospace"
    mask:allowed_chars="1234567890"
    mask:mask="(XXX) XXX-XXXX ext.XXXXXX"
    android:hint="6543215846654321"
    app:keep_hint="true"
    />    
```
(just copy-pasted code from the main page and inserted your values. So, there might be a problem somewhere there, but, I believe, it should work. Please, let me know, if it causes any trouble)
